"""Generated MCP server — READ-ONLY, business-database-scoped.

Generated by the MCP Server Builder. Exposes a single tool, `run_query`, that
executes validated SELECT statements against one configured business database.
Writes, DDL, database-structure/metadata requests (SHOW/DESCRIBE/EXPLAIN),
cross-database access, and overly complex queries are all refused before they
ever reach the database — see the embedded `sql_validator` block below, which
is the exact module covered by the project's test suite.

Security: the database connection string is read from the MCP_DB_URL environment
variable, injected by the deployer at launch. No credentials are written to this
file on disk.

Runs over HTTP (streamable-http) so a host application can connect as an MCP
client and issue read-only queries.
"""

import os
import time

from fastmcp import FastMCP
from sqlalchemy import create_engine, text

# --- SQL validation guard (embedded verbatim from mcp_server/sql_validator.py) ---
__GEN_VALIDATOR_BLOCK__
# --- error classification (embedded verbatim from mcp_server/errors.py) ---------
__GEN_ERRORS_BLOCK__
# --- audit logging (embedded verbatim from mcp_server/audit.py) -----------------
__GEN_AUDIT_BLOCK__
# -------------------------------------------------------------------------------

mcp = FastMCP("__GEN_SERVER_NAME__")

_DB_URL = os.environ.get("MCP_DB_URL")
if not _DB_URL:
    raise RuntimeError(
        "MCP_DB_URL environment variable is required (injected by the deployer)."
    )
_AUDIT_LOG = os.environ.get("MCP_AUDIT_LOG")

# Per-deployment validation config, baked in at generation time.
DB_DIALECT = __GEN_DB_DIALECT__
ALLOWED_DATABASE = __GEN_ALLOWED_DATABASE__
DEFAULT_LIMIT = __GEN_DEFAULT_LIMIT__
MAX_LIMIT = __GEN_MAX_LIMIT__
MAX_JOINS = __GEN_MAX_JOINS__
MAX_SUBQUERY_DEPTH = __GEN_MAX_SUBQUERY_DEPTH__
QUERY_TIMEOUT_MS = __GEN_QUERY_TIMEOUT_MS__

engine = create_engine(_DB_URL, pool_pre_ping=True, pool_recycle=300)


def _apply_timeout(conn) -> None:
    """Best-effort per-query execution budget. Never blocks the actual query
    if the session variable isn't supported on this server/version."""
    try:
        if DB_DIALECT == "mysql":
            conn.execute(text(f"SET SESSION MAX_EXECUTION_TIME = {QUERY_TIMEOUT_MS}"))
        elif DB_DIALECT == "postgres":
            conn.execute(text(f"SET statement_timeout = {QUERY_TIMEOUT_MS}"))
        elif DB_DIALECT == "tsql":
            conn.execute(text(f"SET LOCK_TIMEOUT {QUERY_TIMEOUT_MS}"))
    except Exception:
        pass


@mcp.tool()
def run_query(sql: str):
    """Execute a validated, read-only SELECT query and return the rows.

    INSERT/UPDATE/DELETE/DDL are refused, as are database-structure/metadata
    requests (SHOW/DESCRIBE/EXPLAIN), queries outside the connected business
    database, and queries that exceed the configured complexity limits. Every
    attempt is parsed and validated before execution and audited afterward.
    """
    start = time.monotonic()
    result = validate_sql(
        sql,
        dialect=DB_DIALECT,
        allowed_database=ALLOWED_DATABASE or None,
        default_limit=DEFAULT_LIMIT,
        max_limit=MAX_LIMIT,
        max_joins=MAX_JOINS,
        max_subquery_depth=MAX_SUBQUERY_DEPTH,
    )

    if not result.allowed:
        record(
            _AUDIT_LOG,
            sql=sql,
            allowed=False,
            reason_code=result.reason_code,
            duration_ms=(time.monotonic() - start) * 1000,
        )
        return {"success": False, "message": result.message}

    try:
        with engine.connect() as conn:
            _apply_timeout(conn)
            db_result = conn.execute(text(result.sql))
            fetched = db_result.fetchmany(MAX_LIMIT + 1)
            truncated = len(fetched) > MAX_LIMIT
            rows = [dict(row._mapping) for row in fetched[:MAX_LIMIT]]

        duration_ms = (time.monotonic() - start) * 1000
        record(
            _AUDIT_LOG,
            sql=result.sql,
            allowed=True,
            reason_code="ok",
            duration_ms=duration_ms,
            row_count=len(rows),
        )

        response = {"success": True, "rows": rows, "row_count": len(rows)}
        if truncated:
            response["message"] = (
                f"Results were truncated to {MAX_LIMIT} rows. Please refine your "
                "request (add filters) for a complete result set."
            )
        return response

    except Exception as e:
        duration_ms = (time.monotonic() - start) * 1000
        message = classify_execution_error(e)
        record(
            _AUDIT_LOG,
            sql=result.sql,
            allowed=True,
            reason_code="execution_error",
            duration_ms=duration_ms,
            error=message,
        )
        return {"success": False, "message": message}


if __name__ == "__main__":
    mcp.run(transport="http", host="__GEN_MCP_HOST__", port=__GEN_PORT__)
