"""Generated MCP server — READ-ONLY.

Generated by the MCP Server Builder. Exposes a single tool, `run_query`, that
executes SELECT statements against one database. INSERT, UPDATE, DELETE and every
other write/DDL statement are refused before they ever reach the database.

Security: the database connection string is read from the MCP_DB_URL environment
variable, injected by the deployer at launch. No credentials are written to this
file on disk.

Runs over HTTP (streamable-http) so a host application can connect as an MCP
client and issue read-only queries.
"""

import os

from fastmcp import FastMCP
from sqlalchemy import create_engine, text

# --- read-only guard (embedded verbatim from backend/readonly.py) -------------
{READONLY_BLOCK}
# ------------------------------------------------------------------------------

mcp = FastMCP("{SERVER_NAME}")

_DB_URL = os.environ.get("MCP_DB_URL")
if not _DB_URL:
    raise RuntimeError(
        "MCP_DB_URL environment variable is required (injected by the deployer)."
    )

engine = create_engine(_DB_URL)


@mcp.tool()
def run_query(sql: str):
    """Execute a read-only SELECT query and return the rows.

    INSERT, UPDATE, DELETE and DDL are refused — this server is read-only.
    """

    if not is_read_only(sql):
        return {
            "success": False,
            "message": "Refused: this server is read-only. Only a single SELECT "
                       "statement is allowed (INSERT/UPDATE/DELETE/DDL are out of scope).",
        }

    try:
        with engine.connect() as conn:
            result = conn.execute(text(sql))
            rows = [dict(row._mapping) for row in result]

        return {"success": True, "rows": rows, "row_count": len(rows)}

    except Exception as e:
        return {"success": False, "message": str(e)}


if __name__ == "__main__":
    mcp.run(transport="http", host="{MCP_HOST}", port={PORT})
