"""Generated MCP server — READ-ONLY.

This file is generated by the MCP Server Builder. It exposes a single tool,
`run_query`, that executes SELECT statements against one database. INSERT,
UPDATE, DELETE and every other write/DDL statement are explicitly out of scope
and are refused before they ever reach the database.

It runs over HTTP (streamable-http transport) so a host application — or the
builder itself — can connect as an MCP client and issue read-only queries.
"""

from fastmcp import FastMCP
from sqlalchemy import create_engine, text
import sqlglot
from sqlglot import expressions as exp

mcp = FastMCP("{SERVER_NAME}")

engine = create_engine("{CONNECTION_STRING}")

# Statement types that are always refused. `run_query` additionally requires the
# statement to parse as a bare SELECT, so this list is defence-in-depth.
_FORBIDDEN = (
    exp.Insert, exp.Update, exp.Delete, exp.Merge,
    exp.Create, exp.Drop, exp.Alter, exp.TruncateTable,
    exp.Grant,
)


def is_read_only(sql: str) -> bool:
    """True only if `sql` is a single SELECT (no writes, no DDL, no stacking)."""
    try:
        statements = sqlglot.parse(sql)
    except Exception:
        return False

    # Reject empty input and multi-statement payloads (e.g. "SELECT 1; DROP ...").
    statements = [s for s in statements if s is not None]
    if len(statements) != 1:
        return False

    parsed = statements[0]
    if isinstance(parsed, _FORBIDDEN):
        return False

    return isinstance(parsed, exp.Select)


@mcp.tool()
def run_query(sql: str):
    """Execute a read-only SELECT query and return the rows.

    INSERT, UPDATE, DELETE and DDL are refused — this server is read-only.
    """

    if not is_read_only(sql):
        return {
            "success": False,
            "message": "Refused: this server is read-only. Only a single SELECT "
                       "statement is allowed (INSERT/UPDATE/DELETE/DDL are out of scope).",
        }

    try:
        with engine.connect() as conn:
            result = conn.execute(text(sql))
            rows = [dict(row._mapping) for row in result]

        return {"success": True, "rows": rows, "row_count": len(rows)}

    except Exception as e:
        return {"success": False, "message": str(e)}


if __name__ == "__main__":
    mcp.run(transport="http", host="127.0.0.1", port={PORT})
