[theme]
primaryColor = "#059669"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F172A"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[server]
runOnSave = true
